// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    HeroiconsOutlineHand: typeof import('~icons/heroicons-outline/hand')['default']
    HeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    HeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default']
    HeroiconsOutlineSun: typeof import('~icons/heroicons-outline/sun')['default']
    HeroiconsSolidMinus: typeof import('~icons/heroicons-solid/minus')['default']
    HeroiconsSolidPlus: typeof import('~icons/heroicons-solid/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
